# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel:
        container_name: laravel
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/'
        depends_on:
            - pgsql
    pgsql:
        container_name: pgsql
        image: postgres:13-alpine
        environment:
            - POSTGRES_DB=interview_app
            - POSTGRES_PASSWORD=password
        volumes:
            - .db/:/var/lib/postgresql/data
        ports:
            - 15432:5432
        restart: unless-stopped
